#!/bin/sh

run_latehook() {
	if [ -s /new_root/version ]; then
		echo " Booting [1;37m$(cat /new_root/version)[0m with [1;37m$(uname -srm)[0m."
	else
		echo " Booting [1;37m$(uname -srm)[0m."
	fi
	echo
}
