#!/bin/sh

build() {
	if add_systemd_unit uname.service 2>/dev/null; then
		add_symlink "/usr/lib/systemd/system/sysinit.target.wants/uname.service" "../uname.service"
	else
		add_runscript
	fi
	# busybox provides uname, so we do not add it
}

help() {
	echo "This hook adds an uname output to the boot process."
}
