#!/bin/sh

build() {
	add_systemd_unit uname.service
	add_symlink "/usr/lib/systemd/sysinit.target.wants/uname.service" "../uname.service"
	# busybox provides uname, so we do not add it
}

help() {
	echo "This hook adds an uname output to the boot process."
}
