#!/bin/sh

build() {
	if add_systemd_unit uname.service 2>/dev/null; then
		# busybox provides uname, but the base hook is not prerequisite
		# for a systemd-enable initramfs - so add uname
		add_binary uname

		add_symlink "/usr/lib/systemd/system/sysinit.target.wants/uname.service" "../uname.service"
	else
		add_runscript
	fi
}

help() {
	echo "This hook adds an uname output to the boot process."
}
